#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

start_end_group_name_re_tuples = [
    (
        # start from comment to todo
        re.compile("\*Comment"),
        re.compile("\*Todo"),
        # collect this
        re.compile("\*((?:[A-Z][A-Za-z]+)+)"),
    ),
    (
        re.compile("ColorColumn\tused for the columns set with 'colorcolumn'"),
        re.compile("Tooltip\t\tCurrent font, background and foreground of the tooltips."),
        re.compile("^((?:[A-Z][A-Za-z]+)+)\t"),
    ),
]
start_end_group_name_re_tuple_it = iter(start_end_group_name_re_tuples)

group_names_list = []
(
    start_re, end_re, group_name_re
) = next(start_end_group_name_re_tuple_it)
collecting = False
group_names = []
for line in open('syntax.txt'):

    if start_re.search(line):
        collecting = True

    if not collecting:
        continue

    m = group_name_re.search(line)
    if m:
        group_names.append(m.group(1))

    if end_re.search(line):
        collecting = False
        group_names_list.append(group_names)
        group_names = []
        try:
            (
                start_re, end_re, group_name_re
            ) = next(start_end_group_name_re_tuple_it)
        except StopIteration:
            break

print '# --- generated by parse_syntax_txt.py ---'
print
print 'CONVENTIONAL_GROUP_NAMES = %r' % group_names_list[0]
print
print 'VIM_GROUP_NAMES = %r' % group_names_list[1]
print
print '# --- end ---'
print
print 'count: ', map(len, group_names_list)
